fixtures:
  repositories:
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql"
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    owncloud: "#{source_dir}"
