fixtures:
  repositories:
    apache:              "git://github.com/puppetlabs/puppetlabs-apache"
    apt:
      repo:              "git://github.com/puppetlabs/puppetlabs-apt"
      ref:               "2.0.1"
    # transitive dependency via mounts
    dirtree:             "git://github.com/haw-hh-ai-lab/puppet-dirtree"
    # transitive dependency via mounts
    fstab:               "git://github.com/haw-hh-ai-lab/puppet-fstab.git"
    mounts:              "git://github.com/haw-hh-ai-lab/puppet-mounts.git"
    mysql:               "git://github.com/puppetlabs/puppetlabs-mysql"
    nagios: 
      repo:              "git://github.com/haw-hh-ai-lab/puppet-nagios"
    stdlib: 
      repo:              "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref:               "4.1.0"
  symlinks:
    owncloud: "#{source_dir}"
