fixtures:
  repositories:
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql"
    nagios: 
      repo: "git://github.com/haw-hh-ai-lab/puppet-nagios"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.0.1"
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    owncloud: "#{source_dir}"
