language: ruby
rvm:
  - 1.8.7
script:
    - bundle exec rake spec
branches:
  only:
    - master
    - collab_editor
env:
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.7.4
notifications:
  email:
    - oli@hebbelweg.de
gemfile: .gemfile
